### ISSUE TITLE
Registration failed with tokenHasAlreadyBeenUsed after one unsuccessful registration

### ISSUE THREAD

**Issue by billpage** [escherpad/help-desk#4]
I tried to register when I clicked Submit I received a message saying that my user name 'Bill Page' could not contain a blank character.  When I tried again with user name 'bill.page' I received the message:

"tokenHasAlreadyBeenUsed"

Now, starting over completelty I receive another message:

registration token is invalid! If this problem persists, please get in touch with us!

 It seems that I am no longer able to continue.

Please help. 

bill.page@newsynthesis.org

**Comment by billpage** [comment]
BTW, you do not provide any obvious way to "get in touch with us" ...

**Comment by geyang** [comment]
Hi Bill!!

sorry that is a known bug I need to fix. I am very sorry about this!! I will:
1. fix this bug tonight
2. send you another invitation email as soon as possible.

Sorry about this! 

Also I just setup notification from this help-desk so my response should be faster. I will also add a link to that email!

Ge

**Comment by geyang** [comment]
@billpage update: I just fixed the error message, now working on fixing the bug itself!

![commit screenshot](https://www.dropbox.com/s/3h8d1p8zxrq6y1g/Screenshot%202015-09-17%2022.47.56.png?raw=1)

**Comment by geyang** [comment]
Hi @billpage , I just fixed the bug!!! This problem should never occur anymore.
